name: Add to Project Workflow

on:
  workflow_call:
    inputs:
      project-url:
        description: 'GitHub project URL'
        required: false
        type: string
        default: 'https://github.com/orgs/cgkineo/projects/3/views/1'

jobs:
  add-to-project:
    name: Add to main project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.1.0
        with:
          project-url: ${{ inputs.project-url }}
          github-token: ${{ secrets.ADDTOPROJECT_TOKEN }}
